### ISSUE TITLE
Alternate implementation

### ISSUE THREAD

**Issue by za-creature** [NoobsArePeople2/gulp-luacheck#1]
Hey,

Not sure if you get e-mail notifications for forks, but I've written a [new implementation](https://github.com/za-creature/gulp-luacheck) originally based on yours (I'm pretty much gulp-plugin-illiterate, so having something to start from has been really helpful).

That being said, at this point the fork no longer shares any code with your original implementation (In fact, I've split the luacheck-specific code into a [separate module](https://github.com/za-creature/node-luacheck) which could be useful if anyone wants to pick up the slack and write a Grunt plugin or whatever).

Since both projects are published on npm under the [luacheck](https://www.npmjs.com/package/luacheck) and [gulp-luacheck](https://www.npmjs.com/package/gulp-luacheck) namespaces, and I intend to maintain them in the foreseeable future, could you maybe add a link to them in your README, in case anyone wants a npm-ready version?

Thanks!

**Comment by NoobsArePeople2** [comment]
I don't think I ever got an email about this. Sorry for taking so many months to notice! I've updated the README in my repo to point to your npm listings. 

I'm really glad you've found this little tool to be useful!
